name: Continous Integration
on: [push]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Check code style
        run: npm run lint
      - name: Generate a random JWT secret
        id: generate-secret
        run: echo "::set-output name=JWT_SECRET::$(openssl rand -base64 30)"
        shell: bash        
      - name: Run tests
        run: npm test
        env:
          MONGODB_URI: mongodb+srv://knlklabacka:4V6GWC19dToLUs3N@malkocluster.zwi7e.mongodb.net/?retryWrites=true&w=majority&appName=MalkoCluster
          PORT: 4000
          SALT_ROUNDS: 10
          JWT_SECRET: ${{ steps.generate-secret.outputs.JWT_SECRET }}